CREATE TABLE IF NOT EXISTS MAIL_BOX (
`ID` bigint(20) AUTO_INCREMENT NOT NULL,
  `CODE` varchar(255) NOT NULL,
  `NUMBER` int(11) NOT NULL,
  `STATUS` varchar(1) NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS USER (
`ID` bigint(20) AUTO_INCREMENT NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `FIRSTNAME` varchar(255) DEFAULT NULL,
  `LASTLOGINDATE` datetime DEFAULT NULL,
  `LASTNAME` varchar(255) DEFAULT NULL,
  `LOGINPASSWORD` varchar(255) NOT NULL,
  `STATUS` smallint(6) DEFAULT NULL,
  `CONTACT_NUMBER` varchar(255) DEFAULT NULL,
  `GENDER` char(1) NOT NULL,
  `ROLE` int(11) NOT NULL,
  `USERNAME` varchar(255) NOT NULL,
  `PICLOCATION` varchar(255) DEFAULT NULL,
  `MAILBOX_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  FOREIGN KEY (`MAILBOX_ID`) REFERENCES MAIL_BOX(ID)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS MAIL_ITEM (
`ID` bigint(20) AUTO_INCREMENT NOT NULL,
  `ARRIVALDATE` datetime NOT NULL,
  `BARCODE` varchar(255) DEFAULT NULL,
  `DEPARTUREDATE` datetime NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `USERID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USERID`) REFERENCES USER(ID)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;





					